services:                         
  rpg-mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: sqlserver-rpg
    hostname: mssql
    environment: 
      SA_PASSWORD: Password@123 #Thiết lập password
      ACCEPT_EULA: 'Y'
      # Express: 

    volumes:
      - mssqlvolume:/var/opt/mssql/data # thư mục lưu DB
    ports:
      - "1433:1433"     
                        
volumes:                                
    mssqlvolume:        
      name: sqlserver-rpg-vl
                    
  